name: Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    name: Always Tests
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Hello World!"

  sometimes:
    name: Sometimes Tests
    if: ${{ startsWith(github.ref, 'refs/heads/extra-tests-') }}
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "More Tests!!"